depends:
tcpLess:
  address:
    ip: 0.0.0.0
    port: 900
  limits:
    maxConnections: 10
    maxIdle: 60
    sharedBufferSize: 2048
  tls:
    enabled: true
    caPath: resource/ca.crt
    certPath: resource/server.crt
    keyPath: resource/server.pem